name: Copilot Usage Metrics Export
on:
  workflow_dispatch:

jobs:
  run:
    name: Copilot Usage Metrics Export Action
    runs-on: ubuntu-latest
    steps:
      - uses: bthomas2622/copilot-metrics-export-action@v1.2
        with:
          access-token: ${{ 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}}
          org-summary: true
          org-name: POC-STF-COMPARISON
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
