name: Export Repository Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Esegui ogni giorno a mezzanotte
  push:
    branches:
      - main

jobs:
  export_metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install axios

    - name: Collect repository metrics
      run: node collect-metrics.js

    - name: Upload metrics
      uses: actions/upload-artifact@v3
      with:
        name: repository-metrics
        path: metrics.csv

    env:
      GITHUB_TOKEN: ${{ secrets.GH_METRICS_STORE }}
