name: Run PowerShell Script to export api result from GH

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v1

    - name: Run PowerShell script
      run: pwsh ./script.ps1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_METRICS_STORE }}
